apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: webapp
  labels:
    app: proxy-deployment
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 2
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: halimo2/proxy
        ports:
        - containerPort: 443
